<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Created At' => '',
    'Delete' => '',
    'ID' => '',
    'Receive' => '签收',
    'Reset' => '重置',
    'Sign' => '查询',
    'Update' => '修改',
    'Updated At' => '',
    '修改快递信息: mode' => '',
    'Update Package: mode' => '',
    'Address' => '库位',
    'Company' => '快递公司',
    'Create Package' => '签收',
    'Home' => '主页',
    'Login' => '登录',
    'Packages' => '快递管理',
    'Phone' => '手机',
    'Received At' => '入库时间',
    'Save' => '提交',
    'Search' => '查找',
    'Signing At' => '签收时间',
    'Sn' => '单号',
    'Status' => '状态',
    'The requested page does not exist.' => '您请求的页面不存在。',
];
